### ISSUE TITLE
TaskAfter.cancel(id)

### ISSUE THREAD

**Issue by Qqwy** [OvermindDL1/task_after#1]
I believe one of the most frequent questions people had about the whole timer business, was how to start tasks that could be cancelled.

**Comment by OvermindDL1** [comment]
> I believe one of the most frequent questions people had about the whole timer business, was how to start tasks that could be cancelled.

I'd planned to add function like that, and is indeed why I return the (unique) id, just not got around to it yet due to lack of time yesterday, however I just got a few minutes now so I'll whip it up.  :-)

**Comment by Qqwy** [comment]
If you'd like me to lend a hand with this issue or something else on the library, I'd love to do so, by the way!

**Comment by OvermindDL1** [comment]
> If you'd like me to lend a hand with this issue or something else on the library, I'd love to do so, by the way!

@Qqwy PR's are always welcome if you see features or bug fixed or something that would be useful of course.  :-)

I have a few other ideas that I left the design open to, may or may not do them, but it is definitely open for use.

Just made the changes and tested, about to commit and release a new version.  :-)
