### ISSUE TITLE
Global installation only worked

### ISSUE THREAD

**Issue by hopewise** [OvermindDL1/task_after#2]
Hello,

If I try to install it locally:

```
children = [
  worker(TaskAfter.Worker, [[name: TaskAfter]]),
]
```

, I get this error:

    "TaskAfter: `:name` not defined and no  global name defined"

Any idea?

**Comment by OvermindDL1** [comment]
Hmm, that is exactly the same format that the global method uses internally at:  https://github.com/OvermindDL1/task_after/blob/master/lib/task_after/application.ex#L14

Are you getting that error on startup or when 'calling' TaskAfter (when calling it you have to pass in the name then if not using the global one).  Can you make a minimal example project that shows the error?

Testing it manually shows it works:
```elixir
$ iex -S mix
Interactive Elixir (1.5.0) - press Ctrl+C to exit (type h() ENTER for help)
iex> TaskAfter.Worker.start_link([name: MyName])
{:ok, #PID<0.148.0>}
iex> TaskAfter.task_after(500, fn -> 42 end, send_result: self(), name: MyName)
{:ok, {TaskAfter.Worker, 0}}
iex> flush()
:ok
iex> flush()
42
:ok
```

**Comment by OvermindDL1** [comment]
And yeah, that error is defined at:  https://github.com/OvermindDL1/task_after/blob/bdc3d0c84cef987f453a0213eca2f77864669224/lib/task_after.ex#L41

```elixir
  def task_after(timeout_after_ms, callback, opts \\ []) when is_integer(timeout_after_ms) and is_function(callback, 0) do
    name = opts[:name] || opts[:pid] || Application.get_env(:task_after, :global_name, nil) || throw "TaskAfter:  `:name` not defined and no global name defined"
```
And at cancel and no where else.  You are passing in `:name` into your call, yes?  Without name then it uses the global name if any (otherwise how would it know which one to use?), or it throws that error.

**Comment by hopewise** [comment]
I am having the error when I try to calling TaskAfter, otherwise, the app boots normally with no error.

here is what I get:

```
 TaskAfter.task_after(1000, fn -> IO.puts "Hello" end)
** (throw) "TaskAfter:  `:name` not defined and no global name defined"
    (task_after) lib/task_after.ex:40: TaskAfter.task_after/3
```
How would use a name?

**Comment by OvermindDL1** [comment]
>  TaskAfter.task_after(1000, fn -> IO.puts "Hello" end)

You are not specifying a name, as in the docs you need to pass it to the function and in the error message that it itself tells you (it says you are not passing the `:name` argument).

```elixir
 TaskAfter.task_after(1000, fn -> IO.puts "Hello" end, name: :Blah)
```

All in the docs:  https://hexdocs.pm/task_after/TaskAfter.html#task_after/3

;-)
