### ISSUE TITLE
how to update a task_after time

### ISSUE THREAD

**Issue by tanweerdev** [OvermindDL1/task_after#3]
I need a way to update specific `task_after`'s time call (not very badly needed but if possible support to update parameters passed as well) based on some conditions before that task_after will get called(not every time). Please let me know if I can be of any help

**Comment by OvermindDL1** [comment]
Do you have an idea of usage and API?  Do remember that these are asynchronous so they could potentially run between the calls of you dispatching a change and it receiving it.  In general I think it would be far better to use something like ETS to atomically synchronize data to your waiting task_after processes (and have it clean it up when using it).

**Comment by tanweerdev** [comment]
This is the use case. I have 50 thousand devices and Every device sends a ping msg according to the minimum ping interval set for each device. 
- If we get ping during this interval, the device is online and we reset the task_after for this device. i.e using the device id. Task_after will be having device_id as their id
- If we dont get ping after that interval, we will just consider the device status offline. and we dont  need task_after this time. 
- whenever device pings back we will consider device online

**Comment by tanweerdev** [comment]
And in this particular `Async doesn't matter`

**Comment by OvermindDL1** [comment]
Honestly for that I'd use a single GenServer to handle them all with either ETS or a database (depending on how permanent you want it) storing the last ping time (cached in ETS probably if a database if they ping often, no point if they don't).

A single process per device, although doable by the BEAM, starts to add a lot of overhead, especially if the ping's are UDP.

But yeah, for your thing I'd just register information in ETS to pass back and forth, async still matters as things can flitter in and out even in the midst of another processes executing a single instruction (the beam is non-deterministic across processes, only serialization of events are deterministic between processes, it models the physical reality in that way).  Or at the very least just cancel and re-form it.

It's pretty hard to update 'just' the calls to a function on the beam as anonymous calls are block boxes, so the whole thing would have to be replaced (may as well kill and recreate at that point?), but honestly I'd say store it in ETS.

And really, a process per thing does seem to be the wrong abstraction for this, I would really recommend storing the data in ETS with just a single GenServer managing it (or a pool of genservers via poolboy or so if they are really really active, no more than corecount though).

By the ETS-owning GenServer it can hold it's own knowledge about what is next to ping, although if you use an integer for that (unixtimestamps for example) then you don't even need to do that, just acquire anything less than an amount, and if it starts getting much bigger (50k is starting to get on the edge) then shard them into different keys segmented by a good time for average ping times.

However, I can add something to 'replace' the function call that can happen in a TaskAfter, which would let you change the arguments, just have to be aware that just like calling cancel it may not do anything if the task runs and ends by the time it is received from the point it the command is sent.  Do you still want that considering the above?  :-)

**Comment by OvermindDL1** [comment]
And adding this feature in, I got a little bit of time to do so, publishing as 1.2.0 shortly.  :-)

Also, oh yeah, that was the point of TaskAfter, they don't spawn processes so it is already about as efficient as it can get.  ^.^

**Comment by tanweerdev** [comment]
Thanks

**Comment by OvermindDL1** [comment]
@tanweerdev Do note, the way it stores the times is via an ordered list, for absolutely massive amounts of entries that could start to have an overhead, if you notice it getting to be too much then tell me and I'll shard it into multiple lists as that should fix that decently then (just a lot of refactoring in that case).  :-)

**Comment by tanweerdev** [comment]
Sure. I will also be looking in the code base in free time.
