### ISSUE TITLE
Ownership issue when runing test cases

### ISSUE THREAD

**Issue by tanweerdev** [OvermindDL1/task_after#4]
[warn] TaskAfter: Task `"ping: test_dev!ce"` crashed due to exception: cannot find ownership process for #PID<0.845.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

**Comment by tanweerdev** [comment]
Sorry this was due to not having proper `setup`

**Comment by OvermindDL1** [comment]
Heh, all good.  :-)
